build:
  version: "1.0"

cards:
  message: "Welcome to SWL cards related production APIs "
  contactDetails:
    name: "May Nwe - Product Owner"
    email: "maynwe@swl.com"
  onCallSupport:
    - (95) 9250-1234
    - (66) 8094-1345