spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to SWL accounts related production APIs "
  contactDetails:
    name: "May Nwe - Product Owner"
    email: "maynwe@swl.com"
  onCallSupport:
    - (95) 9250-1234
    - (66) 8094-1345