build:
  version: "3.0"

accounts:
  message: "Welcome to SWL accounts related local APIs "
  contactDetails:
    name: "San Wai - Developer"
    email: "sanwai@swl.com"
  onCallSupport:
    - (95) 9250-1234
    - (66) 8094-1345